### ISSUE TITLE
Add API Routes to Accomplish Stage 1 goals

### ISSUE THREAD

**Issue by bhgrant8** [EMCain/pandaid-api#16]
## Summary

This is a larger tracking ticket regarding adding the API functionality needed to accomplish our Stage 1 goals.

### Sub-Tasks:

API should be able to allow for following behaviors to achieve our Stage 1 goals:

- [ ] Create accounts for individuals
- [ ] Authenticate individuals (log in)
- [ ] Collect information about individual's needs
- [ ] Create master accounts for NPOs
- [ ] Add users to NPOs
- [ ] Authenticate staff in NPOs (log in)
- [ ] Render a list of users based on a filter
- [ ] “Check out”/assign a set of individuals to an NPO
- [ ] Mark individual’s needs as met by an NPO

### Motivation

Users and NPOs will be able to create accounts, and interact
